ALTER TABLE `saved_reports`
    ADD COLUMN `report_schedule` TEXT;

ALTER TABLE `saved_reports`
    ADD COLUMN `report_last_sent_date` DATETIME;

ALTER TABLE `users`
    ADD COLUMN `phone_country_code` VARCHAR(10);

ALTER TABLE `users`
    ADD COLUMN `phone_last_updated` DATETIME;

ALTER TABLE `user_email_preferences`
    ADD COLUMN `notification_method` TINYINT UNSIGNED NOT NULL DEFAULT 1;

ALTER TABLE `user_email_preferences` DROP PRIMARY KEY, ADD PRIMARY KEY(`user_id`, `event_category`, `event_type`, `notification_method`);

CREATE TABLE `user_sms`
(
    `user_sms_id`       INTEGER UNSIGNED   NOT NULL AUTO_INCREMENT,
    `user_id`           MEDIUMINT UNSIGNED NOT NULL,
    `opt_in_date`       DATETIME,
    `opt_out_date`      DATETIME,
    `date_created`      DATETIME           NOT NULL,
    `last_modified`     DATETIME,
    `confirmation_code` VARCHAR(10),
    PRIMARY KEY (`user_sms_id`),
    FOREIGN KEY (`user_id`)
        REFERENCES `users` (`user_id`)
        ON DELETE CASCADE,
    INDEX (`date_created`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET UTF8MB4;


ALTER TABLE `accessories` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `account_activation` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `announcement_groups` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `announcement_resources` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `announcements` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `blackout_instances` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `blackout_series` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `blackout_series_resources` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `credit_log` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `custom_attribute_entities` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `custom_attribute_values` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `custom_attributes` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `custom_time_blocks` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `dbversion` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `group_credit_replenishment_rule` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `group_resource_permissions` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `group_roles` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `groups` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `layouts` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `monitor_views` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `payment_configuration` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `payment_gateway_settings` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `payment_transaction_log` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `peak_times` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `quotas` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `refund_transaction_log` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reminders` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_accessories` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_color_rules` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_files` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_guests` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_instances` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_reminders` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_resources` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_series` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_statuses` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_types` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_users` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reservation_waitlist_requests` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `reset_password_requests` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `resource_accessories` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `resource_group_assignment` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `resource_groups` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `resource_images` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `resource_relationships` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `resource_status_reasons` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `resource_type_assignment` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `resource_types` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `resources` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `roles` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `saved_reports` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `scheduled_job_status` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `schedules` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `terms_of_service` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `time_blocks` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `user_email_preferences` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `user_groups` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `user_preferences` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `user_resource_favorites` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `user_resource_permissions` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `user_session` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `user_sms` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `user_statuses` CONVERT TO CHARACTER SET UTF8MB4;
ALTER TABLE `users` CONVERT TO CHARACTER SET UTF8MB4;